version: '3'
services:
  elm-dev:
    image: elmapp
    volumes:
      - ./webpack.config.js:/app/webpack.config.js
      - ./elm.json:/app/elm.json
      - ./src:/app/src
      - ./dist:/app/dist
    ports:
      - 3000:3000
      - 4000:4000
    command: ["webpack"]
